# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tai's Blog
email: contact@leloctai.com
description: >- # this means to ignore newlines until "baseurl:"
  Blogging stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.leloctai.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: LeLocTai
permalink: pretty

# Build settings
destination: ./docs
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-email-protect
  - jekyll-analytics
#incremental: true

# Plugins settings
jekyll_analytics:
  GoogleAnalytics:
    id: UA-83412074-6
    anonymizeIp: false


# Theme settings
show_excerpts: true
minima:
  social_links:
    twitter: LeLocTai
header_pages:
  


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
