[[redirects]]
  from = "https://tai-blog.netlify.com"
  to = "https://blog.leloctai.com"
  status = 200
  force = true
  
  [[headers]]
  for = "/feed.xml"
    [headers.values]
    Access-Control-Allow-Origin = "*"